version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"https://github.com/Autofleet/.github
  registries:
  - npm-registry-registry-npmjs-org
